routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return redirect('test');
})->name('dashboard');


/**
 * Rutas correspondientes a las respuestas
 */
// Vista para mostrar las respuestas de una pregunta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/question/{id}/showanswers', 'App\Http\Controllers\QuestionController@showanswers');

// Vista para agregar respuestas a una pregunta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/question/{id}/addanswer', 'App\Http\Controllers\QuestionController@addanswer');

// Vista para editar una respuesta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/answer/edit', 'App\Http\Controllers\AnswerController@edit');

// Vista para agregar respuestas al test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/answer', 'App\Http\Controllers\AnswerController');

/**
 * Rutas correspondientes a las Preguntas
 */
// Vista para mostrar las preguntas de un test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/test/{id}/showquestion', 'App\Http\Controllers\TestController@showquestion');

// Vista para agregar preguntas al test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/test/{id}/addquestion', 'App\Http\Controllers\TestController@addquestion');

// Vista para editar una pregunta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/question/edit', 'App\Http\Controllers\QuestionController@edit');

// Vista para agregar preguntas al test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/question', 'App\Http\Controllers\QuestionController');

/**
 * Rutas correspondientes a los tests
 */

// Vista para crear un nuevo test mediante el controlador
Route::get('/test/{id}/show', 'App\Http\Controllers\TestController@show');

// Vista para crear un nuevo test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/test/create', 'App\Http\Controllers\TestController@create');

// Vista para editar un test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/test/edit', 'App\Http\Controllers\TestController@edit');

// Vista para crear un nuevo test mediante su controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/test', 'App\Http\Controllers\TestController');

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\Answer;

class AnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allAnswers = Answer::join('questions', 'questions.id', '=', 'answers.id_question')->get(['answers.*', 'questions.question']); // Se manda a llamar todos los campos de la tabla 'question'
        return view('answers.index')->with('answers', $allAnswers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('answers.create')->with('questions', Question::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $answer = new Answer();
        $answer->id_question = $request->get('id_question');
        $answer->answer = $request->get('answer');
        $answer->isCorrect = ($request->get('isCorrect') == 'on') ? true : false;
        $answer->save();

        return redirect('/test');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $answer['selected'] = Answer::find($id);
        $answer['list'] = Question::all();
        return view('answers.edit')->with('answers', $answer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $answer = Answer::find($id);
        $answer->id_question = $request->get('id_question');
        $answer->answer = $request->get('answer');
        $answer->isCorrect = ($request->get('isCorrect') == 'on') ? true : false;
        $answer->save();

        return redirect('/test');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $answer = Answer::find($id);
        $answer->delete();

        return redirect('/test');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/answers/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Edit an answer') }}
        </h2>
    </x-slot>

    <div class="row container">
        <div class="col-md-12">
            <form action="/answer/{{$answers['selected']->id}}" method="POST">
                <!-- Token -->
                @csrf
                <!-- Especificar metodo PUT -->
                @method('PUT')
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="answer">Answer </label>
                            <input type="text" class="form-control" id="answer" name="answer" value="{{$answers['selected']->answer}}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="question">Choose a question </label>
                        <select class="custom-select" name="id_question">
                            <option disabled selected>Choose a test</option>
                            @foreach ($answers['list'] as $answer)
                            @if($answers['selected']->id_question == $answer->id)
                            <option selected value="{{ $answer->id }}">{{ $answer->question }}</option>
                            @else
                            <option value="{{ $answer->id }}">{{ $answer->question }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-3">
                        <label for="question">Can the user answer anything? </label>
                        <div class="form-group form-check">
                            @if($answers['selected']->isCorrect == '1')
                            <input type="checkbox" checked="true" class="form-check-input" id="isCorrect" name="isCorrect">
                            @else
                            <input type="checkbox" class="form-check-input" id="isCorrect" name="isCorrect">
                            @endif
                            <label class="form-check-label" for="isCorrect">Yes, it's an open question</label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <small class="text-muted">If this answer cannot be answered as correct or incorrect, check the box to indicate that whatever you answer is correct, so for all choices. Remember that this answer will be show as option to choose.</small>
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="col-9">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                    </div>
                    <div class="col-3">
                        <a href="/test" class="btn btn-outline-secondary btn-block">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/answers/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Showing all answers from') }}
        </h2>
    </x-slot>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Question to which it belongs</th>
                        <th scope="col">Answer Text</th>
                        <th scope="col">Is it Correct?</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($answers as $answer)
                    <tr>
                        <td>{{ $answer->id }}</td>
                        <td>{{ $answer->question }}</td>
                        <td>{{ $answer->answer }}</td>
                        <td>{{ ($answer->isCorrect == null) ? 'No':'Yes' }}</td>
                        <td>
                            <div class="row">
                                <div class="col-md-4">
                                    <a href="/answer/{{$answer->id}}/edit" class="btn btn-xs btn-warning btn-block">Edit</a>
                                </div>
                                <div class="col-md-4">
                                    <form action="{{ route('answer.destroy', $answer->id) }}" method="POST">
                                        <!-- Token -->
                                        @csrf
                                        <!-- Especificar metodo PUT -->
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-xs btn-danger btn-block">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>