routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return redirect('test');
})->name('dashboard');


/**
 * Rutas correspondientes a las respuestas
 */
// Vista para mostrar las respuestas de una pregunta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/question/{id}/showanswers', 'App\Http\Controllers\QuestionController@showanswers');

// Vista para agregar respuestas a una pregunta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/question/{id}/addanswer', 'App\Http\Controllers\QuestionController@addanswer');

// Vista para editar una respuesta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/answer/edit', 'App\Http\Controllers\AnswerController@edit');

// Vista para agregar respuestas al test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/answer', 'App\Http\Controllers\AnswerController');

/**
 * Rutas correspondientes a las Preguntas
 */
// Vista para mostrar las preguntas de un test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/test/{id}/showquestion', 'App\Http\Controllers\TestController@showquestion');

// Vista para agregar preguntas al test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->get('/test/{id}/addquestion', 'App\Http\Controllers\TestController@addquestion');

// Vista para editar una pregunta mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/question/edit', 'App\Http\Controllers\QuestionController@edit');

// Vista para agregar preguntas al test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/question', 'App\Http\Controllers\QuestionController');

/**
 * Rutas correspondientes a los tests
 */

// Vista para crear un nuevo test mediante el controlador
Route::get('/test/{id}/show', 'App\Http\Controllers\TestController@show');

// Vista para crear un nuevo test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/test/create', 'App\Http\Controllers\TestController@create');

// Vista para editar un test mediante el controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/test/edit', 'App\Http\Controllers\TestController@edit');

// Vista para crear un nuevo test mediante su controlador
Route::middleware(['auth:sanctum', 'verified'])->resource('/test', 'App\Http\Controllers\TestController');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Answer;
use App\Models\Question;
use App\Models\Test;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allQuestions = Question::join('tests', 'tests.id', '=', 'questions.id_test')->get(['questions.*', 'tests.name_test']); // Se manda a llamar todos los campos de la tabla 'question'
        
        if( count($allQuestions) <= 0 ){
            $allQuestions['no_questions'] = true;
            return view('questions.index')->with('questions', $allQuestions);
        }else{
            return view('questions.index')->with('questions', $allQuestions);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questions.create')->with('tests', Test::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $question = new Question();
        $question->id_test = $request->get('id_test');
        $question->question = $request->get('question');
        $question->isOpen = ($request->get('isOpen') == 'on') ? true : false;
        $question->save();

        return redirect('/test');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $question['selected'] = Question::find($id);
        $question['list'] = Test::all();
        return view('questions.edit')->with('questions', $question);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $question = Question::find($id);
        $question->id_test = $request->get('id_test');
        $question->question = $request->get('question');
        $question->isOpen = ($request->get('isOpen') == 'on') ? true : false;
        $question->save();

        return redirect('/test');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $question = Question::find($id);
        $question->delete();

        return redirect('/test');
    }

    /**
     * Agrega una respuesta a la pregunta
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function addanswer($id = 'none')
    {
        return view('questions.addanswer')->with('id', $id);
    }

    /**
     * Muestra las respuestas de una pregunta
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showanswers($id = 'none')
    {
        $allAnswers = Answer::join('questions', 'questions.id', '=', 'answers.id_question')->where('questions.id', $id)->get(['answers.*', 'questions.question']); // Se manda a llamar todos los campos de la tabla 'question'
        return view('answers.index')->with('answers', $allAnswers);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/questions/addanswer.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Add new answer') }}
        </h2>
    </x-slot>

    <div class="row container">
        <div class="col-md-12">
            <form action="/answer" method="POST">
                @csrf
                <input type="text" value="{{ $id }}" hidden name="id_question" id="id_question">
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <label for="answer">Answer Text </label>
                            <input type="text" class="form-control" id="answer" name="answer" required>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <label for="isCorrect">Is it Correct? </label>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="isCorrect" name="isCorrect">
                            <label class="form-check-label" for="isCorrect">Yes, it is</label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <small class="text-muted">If this answer cannot be answered as correct or incorrect, check the box to indicate that whatever you answer is correct, so for all choices. Remember that this answer will be show as option to choose.</small>
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="col-9">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                    </div>
                    <div class="col-3">
                        <a href="/question" class="btn btn-outline-secondary btn-block">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/questions/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Edit a question') }}
        </h2>
    </x-slot>

    <div class="row container">
        <div class="col-md-12">
            <form action="/question/{{$questions['selected']->id}}" method="POST">
                <!-- Token -->
                @csrf
                <!-- Especificar metodo PUT -->
                @method('PUT')
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="question">Question </label>
                            <input type="text" class="form-control" id="question" name="question" value="{{$questions['selected']->question}}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="question">Choose a test </label>
                        <select class="custom-select" name="id_test">
                            <option disabled selected>Choose a test</option>
                            @foreach ($questions['list'] as $test)
                            @if($questions['selected']->id_test == $test->id)
                            <option selected value="{{ $test->id }}">{{ $test->name_test }}</option>
                            @else
                            <option value="{{ $test->id }}">{{ $test->name_test }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-3">
                        <label for="question">Can the user answer anything? </label>
                        <div class="form-group form-check">
                            @if($questions['selected']->isOpen == '1')
                            <input type="checkbox" checked="true" class="form-check-input" id="isOpen" name="isOpen">
                            @else
                            <input type="checkbox" class="form-check-input" id="isOpen" name="isOpen">
                            @endif
                            <label class="form-check-label" for="isOpen">Yes, it's an open question</label>
                        </div>
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="col-9">
                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                    </div>
                    <div class="col-3">
                        <a href="/test" class="btn btn-outline-secondary btn-block">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/questions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
             
            @if ( count($questions) > 0 )
            {{ __('Showing all questions from') }} {{ $questions[0]->name_test }}
            @else
            {{ __('Nothing to show at this time') }}
            @endif
        </h2>
    </x-slot>

    @if ( count($questions) <= 0 )
        <span class="h2">No hay preguntas aún en este test.</span>
    @else
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name Test</th>
                        <th scope="col">Question</th>
                        <th scope="col">Is it Free Answer?</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($questions as $question)
                    <tr>
                        <td>{{ $question->id }}</td>
                        <td>{{ $question->name_test }}</td>
                        <td>{{ $question->question }}</td>
                        <td>{{ ($question->isOpen == 1) ? 'Yes':'No' }}</td>
                        <td>
                            <div class="row">
                                <div class="col-md-3">
                                    <a href="/question/{{$question->id}}/showanswers" class="btn btn-xs btn-info btn-block">Show Answers</a>
                                </div>
                                @if( $question->isOpen != 1 )
                                <div class="col-md-3">
                                    <a href="/question/{{$question->id}}/addanswer" class="btn btn-xs btn-primary btn-block">Add Answer</a>
                                </div>
                                @endif
                                <div class="col-md-3">
                                    <a href="/question/{{$question->id}}/edit" class="btn btn-xs btn-warning btn-block">Edit</a>
                                </div>
                                <div class="col-md-3">
                                    <form action="{{ route('question.destroy', $question->id) }}" method="POST">
                                        <!-- Token -->
                                        @csrf
                                        <!-- Especificar metodo PUT -->
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-xs btn-danger btn-block">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endif
</x-app-layout>